apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs
parameters:
  adminId: admin
  adminSecretName: ceph-admin-secret
  adminSecretnamespace: ceph-cephfs
  claimRoot: /pvc-volumes
  monitors: 192.168.28.201:6789, 192.168.28.202:6789, 192.168.28.203:6789
provisioner: ceph.com/cephfs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cephfs-provisioner
  namespace: ceph-cephfs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cephfs-provisioner
  namespace: ceph-cephfs
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cephfs-provisioner
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - ""
  resourceNames:
  - kube-dns
  - coredns
  resources:
  - services
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cephfs-provisioner
  namespace: ceph-cephfs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cephfs-provisioner
subjects:
- kind: ServiceAccount
  name: cephfs-provisioner
  namespace: ceph-cephfs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cephfs-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cephfs-provisioner
subjects:
- kind: ServiceAccount
  name: cephfs-provisioner
  namespace: ceph-cephfs
---
apiVersion: v1
data:
  key: QVFDMmdxMVpLVHZ0QlJBQXJpdG1aSmpzM09DNkt5VVJuVThzMkE9PQ==
kind: Secret
metadata:
  name: ceph-admin-secret
  namespace: ceph-cephfs
type: kubernetes.io/rbd
---
apiVersion: v1
data:
  key: QVFDeUNpOWdiRzNlS0JBQStnUVk2RkUwTm1zajZ5aHBhQnNHU1E9PQ==
kind: Secret
metadata:
  name: ceph-ocp-client-secret
  namespace: ceph-cephfs
type: kubernetes.io/rbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cephfs-provisioner
  namespace: ceph-cephfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cephfs-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cephfs-provisioner
    spec:
      containers:
      - args:
        - -id=cephfs-provisioner-1 -v 4
        command:
        - /usr/local/bin/cephfs-provisioner
        env:
        - name: PROVISIONER_NAME
          value: ceph.com/cephfs
        - name: PROVISIONER_SECRET_NAMESPACE
          value: ceph-cephfs
        image: quay.io/external_storage/cephfs-provisioner:latest
        name: cephfs-provisioner
      serviceAccount: cephfs-provisioner
