kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ceph-cephfs
provisioner: ceph.com/cephfs
parameters:
  monitors: 192.168.28.201:6789, 192.168.28.202:6789, 192.168.28.203:6789
  adminId: admin
  adminSecretName: ceph-admin-secret
  adminSecretnamespace: ceph-cephfs
  claimRoot: /pvc-volumes
